language: haskell

env:
  - CABALVER=1.18 GHCVER=7.6.3
  - CABALVER=1.18 GHCVER=7.8.4
  - CABALVER=1.22 GHCVER=7.10.2
  - CABALVER=head GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
  - |
    if [ $GHCVER = `ghc --numeric-version` ]; then
      travis/cabal-apt-install --enable-tests $MODE
      export CABAL=cabal
    else
      # Install the GHC we want from hvr's PPA
      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
      travis_retry sudo apt-get update
      travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
      export CABAL=cabal-$CABALVER
      export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
    fi
  - $CABAL update
  - $CABAL sandbox init
  - cd hask-irc-core;
    $CABAL sandbox init --sandbox=../.cabal-sandbox;
    cd ../hask-irc-handlers;
    $CABAL sandbox init --sandbox=../.cabal-sandbox;
    $CABAL sandbox add-source ../hask-irc-core/;
    cd ../hask-irc-runner;
    $CABAL sandbox init --sandbox=../.cabal-sandbox;
    $CABAL sandbox add-source ../hask-irc-core/;
    $CABAL sandbox add-source ../hask-irc-handlers/;

install:
  - $CABAL install --dependencies-only

script:
  - $CABAL build

  # tests that a source-distribution can be generated
  - cd ../hask-irc-core;
    $CABAL sdist;

  # check that the generated source-distribution can be built & installed
  - export SRC_TGZ=$($CABAL info . | awk '{print $2 ".tar.gz";exit}') ;
    cd dist/;
    if [ -f "$SRC_TGZ" ]; then
       $CABAL install --force-reinstalls "$SRC_TGZ";
    else
       echo "expected '$SRC_TGZ' not found";
       exit 1;
    fi

  # tests that a source-distribution can be generated
  - cd ../hask-irc-handlers;
    $CABAL sdist;

  # check that the generated source-distribution can be built & installed
  - export SRC_TGZ=$($CABAL info . | awk '{print $2 ".tar.gz";exit}') ;
    cd dist/;
    if [ -f "$SRC_TGZ" ]; then
       $CABAL install --force-reinstalls "$SRC_TGZ";
    else
       echo "expected '$SRC_TGZ' not found";
       exit 1;
    fi

  # tests that a source-distribution can be generated
  - cd ../hask-irc-runner;
    $CABAL sdist;

  # check that the generated source-distribution can be built & installed
  - export SRC_TGZ=$($CABAL info . | awk '{print $2 ".tar.gz";exit}') ;
    cd dist/;
    if [ -f "$SRC_TGZ" ]; then
       $CABAL install --force-reinstalls "$SRC_TGZ";
    else
       echo "expected '$SRC_TGZ' not found";
       exit 1;
    fi

notifications:
  email: true
  irc:
    - "irc.immortal-anime.net#animestan-hell"

